# Generated by Django 4.1.7 on 2023-04-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_link', models.CharField(max_length=512)),
                ('thumbnail', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='thumbnail')),
                ('status', models.CharField(choices=[('F', 'Featured'), ('P', 'Popular')], default='F', max_length=1)),
                ('is_published', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
