# Generated by Django 4.1.7 on 2023-04-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
