# Generated by Django 4.1.7 on 2023-04-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_videos_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('phone', models.IntegerField(blank=True, default=0, null=True)),
                ('heading', models.TextField()),
                ('about_desc1', models.TextField(blank=True, null=True)),
                ('about_image', models.ImageField(blank=True, default='about.jpg', null=True, upload_to='aboutImage')),
                ('about_desc2', models.TextField(blank=True, null=True)),
                ('contact_desc', models.TextField(blank=True, null=True)),
                ('contact_image', models.ImageField(blank=True, default='contact.jpg', null=True, upload_to='contactImage')),
                ('social_youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('social_facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('social_twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('social_instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('social_pinterest', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='videos',
            name='duration',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
