# Generated by Django 4.1.7 on 2023-04-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_alter_about_options_alter_videos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='main_banner',
            field=models.ImageField(blank=True, default='main-banner.jpg', null=True, upload_to='mainBanner'),
        ),
    ]
