# Generated by Django 4.1.7 on 2023-04-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='thumbnail',
            field=models.ImageField(blank=True, default='article_default.jpg', null=True, upload_to='articleThumbnail'),
        ),
    ]
